### ISSUE TITLE
Overview: Baking

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#200]
**Task description**

For the Sirius release we are going to add the option to generate baker keys and submit baker transactions from the Concordium Mobile Wallet. 

Just like the delegation options, the baking options will consist of a status screen, and a range of flows used to submit transactions related to baking. 

In Figma, the baking flows can be found below the delegation flows, and there will be a box containing each type of transaction. Some of the transactions will have more than one scenario. Some screens will be semi-transparent, indicating that they are redundant to what have been seen earlier, but they have been kept in the flows to give some contextual information. If you need access to the Figma flows, please reach out to @jens-concordium.

**Sub-tasks**
- [ ] [The baker status page](https://github.com/Concordium/concordium-reference-wallet-ios/issues/201)
- [ ] [The register baker transaction](https://github.com/Concordium/concordium-reference-wallet-ios/issues/202)
- [ ] [The update baker stake transaction](https://github.com/Concordium/concordium-reference-wallet-ios/issues/203)
- [ ] [The update pool settings transaction](https://github.com/Concordium/concordium-reference-wallet-ios/issues/204)
- [ ] [The update baker keys transaction](https://github.com/Concordium/concordium-reference-wallet-ios/issues/205)
- [ ] [The stop baking transaction](https://github.com/Concordium/concordium-reference-wallet-ios/issues/206)

Notes:
- From a technical standpoint there is only one baker transaction, ConfigureBaker. When first registering a baker, all parameters of the transaction must be submitted, but when later updating a baker, the parameters are optional. From the users perspective, there will be the five different transactions mentioned above.

**Comment by EmilLa1** [comment]
These options are available.

**Comment by EmilLa1** [comment]
3.0.0 (48)
