### ISSUE TITLE
Overview: Delegation

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#83]
**Task description**
For the Sirius release we are going to add the option to delegate an amount to an open baker pool, via the Concordium Mobile Wallet. 

The new delegation feature will consist of a handful of new flows and a status page. Each flow and the status page will have their own issues, and this issue can be seen as an overview of them all. 

In Figma, the delegation flows will be laid out in an order, to demonstrate how the states of the delegation can change, and how that will influence the different flows and the status page. Some screens will be semi-transparent, indicating that they are redundant to what have been seen earlier, but they have been kept in the flows to give some contextual information.   If you need access to the Figma flows, please reach out to @jens-concordium.

**Sub-tasks**
- [x] [The delegation status page](https://github.com/Concordium/concordium-reference-wallet-ios/issues/196)
- [x] [Registering a delegation](https://github.com/Concordium/concordium-reference-wallet-ios/issues/197)
- [x] [Updating a current delegation](https://github.com/Concordium/concordium-reference-wallet-ios/issues/198)
- [x] [Stopping a delegation](https://github.com/Concordium/concordium-reference-wallet-ios/issues/199)

Notes:
- From a technical perspective, there is just a single transaction related to delegation, namely the ConfigureDelegation transaction. When first registering a delegation, all parameters must be submitted. Subsequently, when making updates, the parameters are optional. Lastly, submitting a delegation amount of 0, equals stopping a delegation.
- Making an [update transaction](https://github.com/Concordium/concordium-reference-wallet-android/issues/117) that decreases the delegation amount will cause a cool down period for the amount. While the cool down is still pending, no changes can be made to the amount. This also means the delegation cannot be stopped, as that in practice is changing of the amount to 0. This will be reflected on the [delegation status page](https://github.com/Concordium/concordium-reference-wallet-android/issues/115)
- All other changes to a delegation will be locked at the last epoch up to a pay day. Should the transaction be made _during_ the last epoch up to a pay day, the changes will be locked from last epoch up to the _next_ pay day.

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: 3.0.0 (40)
- OS:14.8.1
- Browser
- Mobile device: iPhone SE
